- Gemfile
- Gemfile.lock
- app/controllers/terms_controller.rb
- app/controllers/terms_controller/create_responder.rb
- app/controllers/vocabularies_controller.rb
- app/controllers/vocabularies_controller/create_responder.rb
- app/models/term.rb
- app/services/term_creator.rb
- app/services/vocabulary_creator.rb
- app/views/terms/_form_id.html.erb
- app/views/terms/new.html.erb
- app/views/vocabularies/_form.html.erb
- app/views/vocabularies/new.html.erb
- config/application.rb
- lib/active_triples/not_found.rb
- lib/active_triples_adapter.rb
- spec/controllers/terms_controller_spec.rb
- spec/lib/active_triples_adapter_spec.rb
- spec/mocks/term_mock.rb
- spec/models/term_spec.rb
- spec/rails_helper.rb
- spec/services/term_creator_spec.rb
- spec/services/vocabulary_creator_spec.rb
- spec/support/global_mocks.rb
- spec/views/terms/new.html.erb_spec.rb
- spec/views/vocabularies/new.html.erb_spec.rb
This makes AT act more like AR - making using things like Simple Form way easier.
> Active Triples Wrapper

- app/models/term.rb
- app/services/child_node_finder.rb
- spec/services/child_node_finder_spec.rb
> Add child node finder.

- app/models/vocabulary.rb
Adds Vocabulary properties we use in our JSONLD
> Add title and publisher to Vocabulary

- app/controllers/terms_controller.rb
- app/decorators/term_with_children.rb
- spec/controllers/terms_controller_spec.rb
- spec/decorators/term_with_children_spec.rb
- spec/mocks/term_mock.rb
> Export child graphs for vocabularies.

- app/views/terms/show.html.erb
> Use data lists for displaying properties.

- app/views/terms/_vocab_children.html.erb
- app/views/terms/show.html.erb
> Use header tags for hierarchy, not styling.

- app/views/terms/show.html.erb
> Use #rdf_subject instead of recreating it.

- app/controllers/terms_controller.rb
- app/controllers/vocabularies_controller.rb
- lib/param_cleaner.rb
- spec/controllers/terms_controller_spec.rb
- spec/controllers/vocabularies_controller_spec.rb
- spec/models/term_spec.rb
> Remove blank values from params arrays.

- app/factories/term_factory.rb
- app/services/polymorphic_term_repository.rb
- app/views/terms/edit.html.erb
- lib/term_id.rb
- spec/app_factories/term_factory_spec.rb
- spec/controllers/terms_controller_spec.rb
- spec/lib/term_id_spec.rb
- spec/services/polymorphic_term_repository_spec.rb
- spec/views/terms/edit.html.erb_spec.rb
TermFactory will now spin up a Vocabulary object if appropriate.
Closes #58
> Fix show fields

- app/controllers/vocabularies_controller.rb
- app/injectors/vocabulary_injector.rb
- app/models/term.rb
- app/views/terms/_edit_form.html.erb
- app/views/terms/edit.html.erb
- app/views/terms/show.html.erb
- app/views/vocabularies/edit.html.erb
- config/routes.rb
- spec/controllers/terms_controller_spec.rb
- spec/controllers/vocabularies_controller_spec.rb
- spec/routing/term_routes_spec.rb
- spec/views/terms/edit.html.erb_spec.rb
- spec/views/terms/show.html.erb_spec.rb
- spec/views/vocabularies/edit.html.erb_spec.rb
> Editing Vocabularies

- app/decorators/sets_modified.rb
- app/factories/term_factory.rb
- app/injectors/vocabulary_injector.rb
- app/models/term.rb
- app/services/polymorphic_term_repository.rb
- spec/app_factories/term_factory_spec.rb
- spec/decorators/sets_modified_spec.rb
- spec/models/term_spec.rb
This is composition over inheritance.
> Extract Modified Behavior

- app/views/shared/_navbar.html.erb
> home link on navbar

- app/queries/all_vocabs_query.rb
- lib/solutions_to_graph.rb
- lib/subjects_to_graph.rb
This should help make query objects easier.
> Extract collaborators for AllVocabsQuery.

- app/validators/terms_are_importable.rb
- spec/models/importable_term_list_spec.rb
- spec/validators/importable_term_spec.rb
Don't validate importable terms with TermIsUnique.
Closes #111
> Importable Terms

- app/services/child_node_finder.rb
- spec/services/child_node_finder_spec.rb
Fixes #72 
No ui or options, just sorting. is this enough for now?
> add sort to results

- app/views/terms/show.html.erb
- app/views/vocabularies/index.html.erb
> make create and edit links look like buttons

- app/views/home/index.html.erb
- app/views/import_rdf/index.html.erb
- app/views/import_rdf/preview_import.html.erb
- app/views/layouts/application.html.erb
- app/views/login/index.html.erb
- app/views/terms/404.html.erb
- app/views/terms/edit.html.erb
- app/views/terms/new.html.erb
- app/views/terms/show.html.erb
- app/views/vocabularies/edit.html.erb
- app/views/vocabularies/index.html.erb
- app/views/vocabularies/new.html.erb
fixes #60 
not sure that this is the most efficient way to do this
> descriptive titles

- Gemfile
- Gemfile.lock
- app/controllers/terms_controller.rb
- app/controllers/vocabularies_controller.rb
- app/decorators/sets_attributes.rb
- app/injectors/vocabulary_injector.rb
- app/services/graph_to_importable_term_list.rb
- app/views/vocabularies/_form_attribute.html.erb
- spec/controllers/terms_controller_spec.rb
- spec/controllers/vocabularies_controller_spec.rb
- spec/decorators/sets_attributes_spec.rb
- spec/decorators/sets_modified_spec.rb
- spec/features/create_term_spec.rb
Fixes #103 
One thing that is not covered by this PR is attaching languages to the import process. A ticket was made to cover this.
> Adds RDF::Literal and language to rdf graph via vocab and term ingest.

- app/assets/javascripts/analytics.js
- app/assets/javascripts/application.js
- app/views/layouts/application.html.erb
- app/views/shared/_analytics.html.erb
- spec/support/poltergeist.rb
> Google Analytics

- app/assets/stylesheets/template.css.scss
> Added margin to body so footer doesn't overlap page content.

- app/assets/stylesheets/template.css.scss
> Added important to margin-bottom so it's not overruled by margin: 0.

- app/assets/javascripts/multi_value_fields.js.coffee
- app/assets/stylesheets/template.css.scss
- app/views/vocabularies/_form_attribute.html.erb
- app/views/vocabularies/_form_attribute_with_index.html.erb
This should fix the issue of deleting the default field when removing the last one using the remove button
Updated the layout on the language field, so that it is smaller than the input field on the view
> updated form layout and custom js for remove button

- app/models/term.rb
> Reordered properties for a more logical order.

- app/views/shared/_navbar.html.erb
- spec/views/shared/_navbar.html.erb_spec.rb
> hide import external rdf link when not logged in

- Gemfile.lock
- app/views/vocabularies/_form_attribute.html.erb
- app/views/vocabularies/_form_attribute_with_index.html.erb
- lib/controlled_vocab_manager/iso_language_translator.rb
- spec/features/create_term_spec.rb
- spec/lib/controlled_vocab_manager/iso_language_translator_spec.rb
Fixes #175 Adds a new method to request a sorted list of languages. Can be extended to sort in specific ways if need be.
> Added sorted language list method and sorting dropdown.

- app/assets/javascripts/managed_field_add_listener.js
- app/views/vocabularies/_form_attribute.html.erb
- app/views/vocabularies/_form_attribute_with_index.html.erb
- app/views/vocabularies/_language_select.html.erb
- spec/features/create_term_spec.rb
- spec/ui/default_language_select_spec.rb
> fixes default language select list bug, refactors the select

- app/injectors/vocabulary_injector.rb
- spec/queries/all_vocabs_query_spec.rb
- spec/services/child_node_finder_spec.rb
> updated vocab injector and specs to query test context

- app/views/home/index.html.erb
> Added homepage text written by Julia, with a few minor edits.

- app/assets/stylesheets/institution.css
- app/views/devise/registrations/new.html.erb
- lib/tasks/admin_user.rake
This adds a task to easily generate an admin user.
> Admin user rake task and small style edit

- app/views/shared/_navbar.html.erb
> Fix top nav formatting

- Gemfile
- Gemfile.lock
- app/assets/javascripts/add_date_field.js.coffee
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/views/vocabularies/_form_attribute_with_index.html.erb
> added datepicker for date field

- app/injectors/vocabulary_injector.rb
> Comments out sparql in all vocabs query

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.css.scss
- app/views/shared/_navbar.html.erb
fixes #255 
This fixes the hamburger button not showing on mobile screens. One way that I found useful to avoid overflowing the menu to two lines was to use a dropdown menu for admin user actions.
> updated navbar view

- app/decorators/term_with_children.rb
- app/decorators/term_without_children.rb
> adding newlines for the nts

- app/assets/javascripts/term_type_select.js
- app/views/vocabularies/_form_attribute.html.erb
- app/views/vocabularies/_form_attribute_list.html.erb
- app/views/vocabularies/_form_attribute_with_index.html.erb
> Fix Label not showing up.

- Gemfile.lock
> updates triplestore-adapter gem for rake task functionality

- app/views/terms/_term_row.html.erb
> Changed language display to use Bootstrap label.

- app/models/term.rb
This is related to #289 
It doesn't really fix it directly, but should prevent the errors currently happening.
> Added 'range' to blacklisted_language_properties.

- app/assets/stylesheets/application.css.scss
> brighten contrast to pass WAVE accessibility tests

- app/models/term.rb
> Added 'domain' to blacklisted_language_properties

- app/assets/stylesheets/application.css.scss
- app/decorators/sets_term_type.rb
- app/decorators/term_with_children.rb
- app/injectors/term_injector.rb
- app/models/term.rb
- app/models/term_type.rb
- app/repositories/deprecate_term_form_repository.rb
- app/repositories/term_form_repository.rb
- app/services/graph_to_terms.rb
- app/services/polymorphic_term_repository.rb
- app/views/terms/_term_row.html.erb
- app/views/terms/_term_row_type.html.erb
- app/views/terms/_term_types_select.html.erb
- app/views/terms/_vocab_children.html.erb
- app/views/terms/edit.html.erb
- app/views/terms/show.html.erb
- spec/models/term_spec.rb
- spec/models/term_type_spec.rb
- spec/views/terms/new.html.erb_spec.rb
> TermType serialization/deserialization functionality and UI

- Gemfile
- app/controllers/admin/users_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- app/views/admin/users/edit.html.erb
- config/initializers/simple_form.rb
- spec/controllers/predicates_controller_spec.rb
- spec/controllers/terms_controller_spec.rb
- spec/controllers/users/registrations_controller_spec.rb
- spec/controllers/vocabularies_controller_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
- spec/views/terms/show.html.erb_spec.rb
Fixes #286 Fixes #287 Fixes #320
This implements stacked roles. We switched from using check boxes to using radio buttons to implement stacked roles. 
Role list:
Admin reviewer editor
reviewer editor
editor
Adds user tests and adds both client side and backend validation.
> Adds user validations for frontend and backend and simpleform for roles

- Gemfile.lock
- app/views/shared/_navbar.html.erb
- config/routes.rb
- spec/controllers/import_rdf_controller_spec.rb
- spec/views/import_rdf/_form.html.erb_spec.rb
- spec/views/import_rdf/_termlist.html.erb_spec.rb
- spec/views/import_rdf/index.html.erb_spec.rb
- spec/views/import_rdf/preview_import.html.erb_spec.rb
> Disable rdf import links and routes. Make tests pending

- Gemfile
- Gemfile.lock
- app/models/term.rb
- app/models/vocabulary.rb
> includes rdf-vocab gem, and updates RDF::DC usages

- app/services/rdf_loader.rb
- app/services/triplestore_loader.rb
- lib/tasks/git_triplestore_sync.rake
- spec/services/rdf_loader_spec.rb
- spec/services/triplestore_loader_spec.rb
> Triplestore sync to load from a file, and includes full spec coverage and rake

- spec/features/create_term_spec.rb
- spec/features/create_vocabulary_spec.rb
- spec/rails_helper.rb
- spec/support/capybara_login.rb
- spec/support/capybara_screenshot.rb
- spec/support/devise.rb
Fixes the random failures for the feature specs and removes capybara screenshot deprecations and devise deprecations
> Fixes deprecations and intermittent failures

- app/views/admin/index.html.erb
> disable the link until Import features work properly with Git 

- app/services/graph_to_terms.rb
> defaults to Term when there aren't valid types in the statements

- app/injectors/deprecate_predicate_injector.rb
- app/injectors/deprecate_term_injector.rb
- app/injectors/deprecate_vocabulary_injector.rb
- app/repositories/deprecate_predicate_form_repository.rb
- app/repositories/deprecate_term_form_repository.rb
- spec/forms/deprecate_predicate_form_spec.rb
- spec/forms/deprecate_term_form_spec.rb
- spec/forms/deprecate_vocabulary_form_spec.rb
- spec/repositories/deprecate_predicate_form_repository_spec.rb
- spec/repositories/deprecate_term_form_repository_spec.rb
- spec/repositories/deprecate_vocabulary_form_repository_spec.rb
> Deprecate term, vocabulary, predicate. 

- app/controllers/predicates_controller.rb
- app/controllers/terms_controller.rb
- app/controllers/vocabularies_controller.rb
- app/views/terms/_term_types_select.html.erb
- spec/controllers/terms_controller_spec.rb
- spec/features/create_term_spec.rb
- spec/support/pages/term_review_show_page.rb
> fix types for review edits

- Gemfile
> capistrano in gemfile for deployment

- app/controllers/concerns/git_interface.rb
> fixes triplestore persistence for multi-values

- app/controllers/concerns/git_interface.rb
- app/controllers/predicates_controller.rb
- app/controllers/terms_controller.rb
- app/controllers/vocabularies_controller.rb
- spec/controllers/git_interface_spec.rb
- spec/controllers/predicates_controller_spec.rb
- spec/controllers/terms_controller_spec.rb
- spec/controllers/vocabularies_controller_spec.rb
see comments for the other PR, 371
> check for index.lock prob before preceding with creates or updates

- Gemfile
- Gemfile.lock
- config/newrelic.yml
> add New Relic for app performance reporting

- app/controllers/review_controller.rb
- spec/controllers/review_controller_spec.rb
> require admin for review show and index

- app/controllers/concerns/git_interface.rb
- app/controllers/review_controller.rb
- spec/controllers/review_controller_spec.rb
> handle review show and edit when term not found

- app/assets/javascripts/application.js
- app/assets/javascripts/update_user_data_on_cached_page.js
- app/assets/stylesheets/application.css.scss
- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/controllers/predicates_controller.rb
- app/controllers/terms_controller.rb
- app/controllers/vocabularies_controller.rb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- app/views/terms/show.html.erb
- config/routes.rb
- spec/views/terms/show.html.erb_spec.rb
fixes #376 
add page enhancement using ajax for Terms#show
cache Terms#show without user specific nav or buttons
> caches basic show page, enhances view on document.ready()

- app/values/maybe_uri.rb
- spec/values/maybe_uri.rb
> dont convert string uris

- app/controllers/concerns/git_interface.rb
> closes git repo when appropriate

- Gemfile
- Gemfile.lock
- app/controllers/import_rdf_controller.rb
- app/forms/import_form.rb
- app/forms/load_form.rb
- app/models/term.rb
- app/services/rdf_loader.rb
- app/services/triplestore_loader.rb
- app/validators/terms_are_importable.rb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- spec/controllers/import_rdf_controller_spec.rb
- spec/features/import_rdf_term_spec.rb
- spec/features/load_rdf_term_spec.rb
- spec/forms/import_form_spec.rb
- spec/forms/load_form_spec.rb
- spec/services/rdf_importer_spec.rb
- spec/services/rdf_loader_spec.rb
- spec/validators/importable_term_spec.rb
- spec/views/import_rdf/_form.html.erb_spec.rb
- spec/views/import_rdf/_termlist.html.erb_spec.rb
- spec/views/import_rdf/index.html.erb_spec.rb
- spec/views/import_rdf/preview_import.html.erb_spec.rb
- spec/views/shared/_navbar.html.erb_spec.rb
fixes #386 
A lot of files got touched because everything was turned off.
The main additions are some new tests and the git stuff in import_rdf_controller.
> add bulk imports to git

- app/controllers/concerns/git_interface.rb
- app/views/review/index.html.erb
- spec/views/review/index.html.erb_spec.rb
> add author to review index

- app/views/review/show.html.erb
> Include term_row_type partial to match terms/show code.

- app/controllers/review_controller.rb
- app/views/review/show.html.erb
- spec/features/create_term_spec.rb
- spec/support/poltergeist.rb
- spec/views/review/show.html.erb_spec.rb
to get us through the next couple of weeks.
> turn off change hist

- app/views/terms/show.html.erb
> use termid for links

- app/views/review/edit.html.erb
- app/views/review/show.html.erb
- app/views/terms/_edit_form.html.erb
- circle.yml
- config/routes.rb
- spec/features/create_term_spec.rb
- spec/features/load_rdf_term_spec.rb
- spec/rails_helper.rb
> Update term review update button

- app/views/review/edit.html.erb
- app/views/review/show.html.erb
- app/views/terms/_edit_form.html.erb
- circle.yml
- config/routes.rb
- spec/features/create_term_spec.rb
- spec/features/load_rdf_term_spec.rb
- spec/rails_helper.rb
Reverts OregonDigital/ControlledVocabularyManager#443
sorry yall. Will do it right this time.
> Revert "Update term review update button"

- app/views/vocabularies/_form.html.erb
> required id field

- app/views/predicates/_form.html.erb
- app/views/terms/_form_id.html.erb
> term and predicate

- app/controllers/predicates_controller.rb
> Fixes id grabbing when displaying flash message

- app/views/terms/show.html.erb
> Sort by label

- app/controllers/import_rdf_controller.rb
- app/controllers/predicates_controller.rb
- app/controllers/review_controller.rb
- app/controllers/terms_controller.rb
- app/controllers/vocabularies_controller.rb
- spec/controllers/predicates_controller_spec.rb
- spec/controllers/review_controller_spec.rb
- spec/controllers/terms_controller_spec.rb
- spec/controllers/vocabularies_controller_spec.rb
> Update flash types, adjust specs to match.

- app/decorators/term_with_children.rb
- app/decorators/term_without_children.rb
- spec/decorators/term_with_children_spec.rb
fixes #441 
I discovered that the inject is a nice construct here, but the graph doesn't get turned into a string unless there's at least 2 statements, so I added one in the spec, but is it safe to say that there will always be >= 2 statements? I can add more code otherwise.
> gsub is not the answer

- app/assets/stylesheets/application.css.scss
- app/views/terms/_form_id.html.erb
- config/locales/en.yml
> form hint for id.

- app/controllers/review_controller.rb
> Add parentheses to ensure ternary evaluates.

- app/views/review/edit.html.erb
- app/views/review/show.html.erb
> Fixes review titles

- app/controllers/concerns/git_interface.rb
- spec/controllers/git_interface_spec.rb
> delete branch if content empty

- Gemfile.lock
Ran bundle install locally from latest changes.
> Update Gemfile.lock with no therubyracer.

- Gemfile
- Gemfile.lock
> Bump gem versions, including patch bump for rails.

- .circleci/config.yml
- Gemfile.lock
Also switched CircleCI image due to issues with installing packages from jessie sources. https://github.com/circleci/circleci-images/issues/370
> Devise update

- app/assets/stylesheets/application.css.scss
- app/controllers/terms_controller.rb
- app/models/local_collection.rb
- app/models/predicate.rb
- app/models/term.rb
- app/models/term_type.rb
- app/models/vocabulary.rb
- app/views/terms/_term_row.html.erb
- app/views/vocabularies/_form_attribute_list.html.erb
- config/locales/en.yml
- spec/models/term_spec.rb
- spec/models/term_type_spec.rb
- spec/services/graph_to_terms_spec.rb
> Local collection type, with Ark and Local properties

- Gemfile
- Gemfile.lock
- app/controllers/terms_controller.rb
Add Brakeman to Gemfile development group.
Don't run .constantize on params[:term_type], check against whitelist instead
> Whitelist term type

- README.md
> Move blazegraph start sooner. Add admin user section.

- config/sunspot.yml
Fixes #544 
I mistakenly had git stash'd this config value while doing some of the gem updates and branch switching.
> Update sunspot config for solr

- app/assets/stylesheets/application.css.scss
> override navbar-toggle float behavior

- Gemfile.lock
> Add updated Gemfile.lock after bundle install

- Gemfile
- Gemfile.lock
On deploy mysql2 had a LoadError.
> Relax mysql2 version to bump up.

- Gemfile
- Gemfile.lock
mysql2 gem version 0.5.3 didn't want to build on the production server
> Change the mysql2 gem version to 0.4.x

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
Rebuilt associated files from capistrano generator for v3.
> Update capistrano to v3, incl. Capfile and deploy.rb

- config/application.rb
- config/deploy.rb
- config/deploy/production.rb
Add /lib to eager_load_path for production. Reduce linked folders in tmp.
> Update task syntax to v3.

- app/views/shared/_navbar.html.erb
- config/environments/production.rb
> Update devise to force ssl and update login link.

- Gemfile
- Gemfile.lock
Old version was hard-coded from Rails generator.
> Remove hard-coded old version for sdoc.
